from __future__ import annotations

import argparse
import html
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "architecture.svg"

PALETTE = {
    "ink": "#2b3a42",
    "sub": "#6b7a80",
    "line": "#aeb8b8",
    "boundary_line": "#dcd4c9",
    "boundary_fill": "#faf9f7",
    "input_fill": "#e4eaed",
    "input_line": "#9eb2bb",
    "mutable_fill": "#e9eeec",
    "mutable_line": "#9aaca4",
    "protected_fill": "#e5eaed",
    "protected_line": "#8fa3ad",
    "evidence_fill": "#f5ebe3",
    "evidence_line": "#c9a98c",
}


def tag(name: str, **attributes: object) -> str:
    attrs = " ".join(f'{key.removesuffix("_").replace("_", "-")}="{value}"' for key, value in attributes.items())
    return f"  <{name} {attrs}/>"


def text(value: str, x: int, y: int, class_: str, anchor: str | None = None) -> str:
    anchor_attr = f' text-anchor="{anchor}"' if anchor else ""
    return f'  <text x="{x}" y="{y}"{anchor_attr} class="{class_}">{html.escape(value)}</text>'


def rect(x: int, y: int, width: int, height: int, radius: int, class_: str) -> str:
    return tag("rect", x=x, y=y, width=width, height=height, rx=radius, class_=class_)


def line(x1: int, y1: int, x2: int, y2: int, class_: str = "flow") -> str:
    return tag("line", x1=x1, y1=y1, x2=x2, y2=y2, class_=class_)


def path(points: str, class_: str = "flow") -> str:
    return tag("path", d=points, class_=class_)


def arrow(x: int, y: int, direction: str) -> str:
    if direction == "down":
        points = f"{x},{y} {x - 5},{y - 9} {x + 5},{y - 9}"
    elif direction == "up":
        points = f"{x},{y} {x - 5},{y + 9} {x + 5},{y + 9}"
    elif direction == "right":
        points = f"{x},{y} {x - 9},{y - 5} {x - 9},{y + 5}"
    elif direction == "left":
        points = f"{x},{y} {x + 9},{y - 5} {x + 9},{y + 5}"
    else:
        raise ValueError(f"unsupported arrow direction: {direction}")
    return tag("polygon", points=points, class_="arrow-fill")


def box(
    x: int,
    y: int,
    width: int,
    height: int,
    class_: str,
    title: str,
    subtitle: str | None = None,
) -> list[str]:
    center = x + width // 2
    title_y = y + (32 if subtitle else 35)
    result = [rect(x, y, width, height, 12 if height > 60 else 10, class_), text(title, center, title_y, "title", "middle")]
    if subtitle:
        result.append(text(subtitle, center, y + 56, "body", "middle"))
    return result


def style() -> str:
    return f"""  <style>
    text {{ font-family: \"Noto Sans SC\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif; fill: {PALETTE['ink']}; }}
    .section-label {{ font-size: 15px; font-weight: 600; letter-spacing: 0.04em; fill: {PALETTE['sub']}; }}
    .title {{ font-size: 20px; font-weight: 600; }}
    .body {{ font-size: 15px; fill: {PALETTE['sub']}; }}
    .small {{ font-size: 13px; fill: {PALETTE['sub']}; }}
    .node-label {{ font-size: 15px; font-weight: 600; }}
    .canvas {{ fill: #ffffff; }}
    .surface {{ fill: #ffffff; stroke: {PALETTE['line']}; stroke-width: 1.5; }}
    .input {{ fill: {PALETTE['input_fill']}; stroke: {PALETTE['input_line']}; stroke-width: 1.5; }}
    .mutable {{ fill: {PALETTE['mutable_fill']}; stroke: {PALETTE['mutable_line']}; stroke-width: 1.5; }}
    .protected {{ fill: {PALETTE['protected_fill']}; stroke: {PALETTE['protected_line']}; stroke-width: 1.5; }}
    .evidence {{ fill: {PALETTE['evidence_fill']}; stroke: {PALETTE['evidence_line']}; stroke-width: 1.5; }}
    .boundary {{ fill: {PALETTE['boundary_fill']}; stroke: {PALETTE['boundary_line']}; stroke-width: 1.5; stroke-dasharray: 7 6; }}
    .flow {{ fill: none; stroke: {PALETTE['line']}; stroke-width: 1.7; }}
    .arrow-fill {{ fill: {PALETTE['line']}; }}
  </style>"""


def render() -> str:
    svg = [
        '<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="768" viewBox="0 0 1200 720" role="img" aria-labelledby="title description">',
        "  <!-- Generated by tools/generate_architecture_svg.py. -->",
        "  <title id=\"title\">Evolve Framework architecture</title>",
        "  <desc id=\"description\">A meta-agent outer loop evolves candidates across generations. Inside it, a worker agent executes tasks through tools and environment observations. The protected runtime evaluates each candidate and retains evidence.</desc>",
        style(),
        "",
        rect(0, 0, 1200, 720, 0, "canvas"),
        "",
        text("EXPERIMENT INPUTS", 60, 28, "section-label"),
        "",
    ]

    inputs = (
        (60, "Recipe", "strategy + mutable surface"),
        (450, "Target seed", "worker agent + context"),
        (840, "Task dataset", "train + gate + sealed tasks"),
    )
    for x, title, subtitle in inputs:
        svg.extend(box(x, 45, 300, 76, "input", title, subtitle))
        svg.append("")

    svg.extend(
        [
            rect(40, 150, 1120, 435, 18, "boundary"),
            rect(60, 137, 338, 28, 14, "surface"),
            text("OUTER LOOP · META-AGENT EVOLUTION", 229, 156, "section-label", "middle"),
            "",
            path("M 210 121 V 180 H 150 V 206"),
            arrow(150, 215, "down"),
            path("M 600 121 V 180 H 475"),
            arrow(475, 189, "down"),
            path("M 990 121 V 180 H 1035 V 206"),
            arrow(1035, 215, "down"),
            "",
            rect(70, 215, 160, 72, 12, "surface"),
            text("Select parent", 150, 247, "title", "middle"),
            text("archive + recipe", 150, 271, "body", "middle"),
            "",
            rect(275, 190, 400, 285, 16, "surface"),
            text("INNER LOOP · WORKER EXECUTION", 300, 220, "section-label"),
            "",
            rect(305, 245, 140, 58, 10, "surface"),
            text("Task + context", 375, 280, "node-label", "middle"),
            rect(505, 245, 140, 58, 10, "mutable"),
            text("Worker Agent", 575, 280, "node-label", "middle"),
            rect(505, 355, 140, 58, 10, "protected"),
            text("Tools + env", 575, 390, "node-label", "middle"),
            rect(305, 355, 140, 58, 10, "surface"),
            text("Observation", 375, 390, "node-label", "middle"),
            line(445, 274, 496, 274),
            arrow(505, 274, "right"),
            line(575, 303, 575, 346),
            arrow(575, 355, "down"),
            line(505, 384, 454, 384),
            arrow(445, 384, "left"),
            path("M 375 355 V 329 H 575 V 312"),
            arrow(575, 303, "up"),
            "",
            rect(710, 215, 190, 135, 14, "mutable"),
            text("META AGENT", 735, 242, "section-label"),
            text("Analyze + edit", 805, 275, "node-label", "middle"),
            text("edit target / operators", 735, 300, "body"),
            text("produce candidate patch", 735, 326, "small"),
            "",
            rect(950, 215, 170, 135, 14, "protected"),
            text("FROZEN PATH", 975, 242, "section-label"),
            text("Evaluate + gate", 1035, 275, "node-label", "middle"),
            text("stamp score", 975, 300, "body"),
            text("record generation", 975, 326, "small"),
            "",
            line(230, 251, 266, 251),
            arrow(275, 251, "right"),
            line(675, 274, 701, 274),
            arrow(710, 274, "right"),
            line(900, 282, 941, 282),
            arrow(950, 282, "right"),
            path("M 1035 350 V 490 H 150 V 296"),
            arrow(150, 287, "up"),
            text("stamped evidence · next generation", 590, 511, "small", "middle"),
            "",
            path("M 805 350 V 445 H 684"),
            arrow(675, 445, "left"),
            text("candidate patch", 742, 465, "small", "middle"),
            "",
            rect(275, 530, 845, 38, 10, "protected"),
            text("PROTECTED CONTROL PLANE", 300, 555, "section-label"),
            text("vendored runtime · frozen evaluator · surface checks · score stamps", 1095, 555, "body", "end"),
        ]
    )
    svg.extend(
        [
            text("EVIDENCE AND LINEAGE", 60, 615, "section-label"),
            "",
        ]
    )

    evidence = ((60, "Git generation tags"), (450, "archive.jsonl"), (840, "Trajectories and artifacts"))
    for x, label in evidence:
        svg.extend(box(x, 630, 300, 58, "evidence", label))
    svg.extend(
        [
            "",
            path("M 700 568 V 600 H 210 V 621"),
            arrow(210, 630, "down"),
            path("M 700 600 H 600 V 621"),
            arrow(600, 630, "down"),
            path("M 700 600 H 990 V 621"),
            arrow(990, 630, "down"),
            "</svg>",
        ]
    )
    return "\n".join(svg) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the README architecture diagram.")
    parser.add_argument("--check", action="store_true", help="Fail if docs/architecture.svg is not up to date.")
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date; regenerate it with {Path(__file__).relative_to(ROOT)}")
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is up to date")
        return 0
    OUTPUT.write_text(generated)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
