from __future__ import annotations

import argparse
import html
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "architecture.svg"

PALETTE = {
    "ink": "#2b3a42",
    "sub": "#6b7a80",
    "line": "#aeb8b8",
    "boundary_line": "#dcd4c9",
    "boundary_fill": "#faf9f7",
    "input_fill": "#e4eaed",
    "input_line": "#9eb2bb",
    "mutable_fill": "#e9eeec",
    "mutable_line": "#9aaca4",
    "protected_fill": "#e5eaed",
    "protected_line": "#8fa3ad",
    "evidence_fill": "#f5ebe3",
    "evidence_line": "#c9a98c",
}


def tag(name: str, **attributes: object) -> str:
    attrs = " ".join(f'{key.removesuffix("_").replace("_", "-")}="{value}"' for key, value in attributes.items())
    return f"  <{name} {attrs}/>"


def text(value: str, x: int, y: int, class_: str, anchor: str | None = None) -> str:
    anchor_attr = f' text-anchor="{anchor}"' if anchor else ""
    return f'  <text x="{x}" y="{y}"{anchor_attr} class="{class_}">{html.escape(value)}</text>'


def rect(x: int, y: int, width: int, height: int, radius: int, class_: str) -> str:
    return tag("rect", x=x, y=y, width=width, height=height, rx=radius, class_=class_)


def line(x1: int, y1: int, x2: int, y2: int, class_: str = "flow") -> str:
    return tag("line", x1=x1, y1=y1, x2=x2, y2=y2, class_=class_)


def path(points: str, class_: str = "flow") -> str:
    return tag("path", d=points, class_=class_)


def arrow(x: int, y: int, direction: str) -> str:
    if direction == "down":
        points = f"{x},{y} {x - 5},{y - 9} {x + 5},{y - 9}"
    elif direction == "up":
        points = f"{x},{y} {x - 5},{y + 9} {x + 5},{y + 9}"
    elif direction == "right":
        points = f"{x},{y} {x - 9},{y - 5} {x - 9},{y + 5}"
    else:
        raise ValueError(f"unsupported arrow direction: {direction}")
    return tag("polygon", points=points, class_="arrow-fill")


def box(
    x: int,
    y: int,
    width: int,
    height: int,
    class_: str,
    title: str,
    subtitle: str | None = None,
) -> list[str]:
    center = x + width // 2
    title_y = y + (32 if subtitle else 35)
    result = [rect(x, y, width, height, 12 if height > 60 else 10, class_), text(title, center, title_y, "title", "middle")]
    if subtitle:
        result.append(text(subtitle, center, y + 56, "body", "middle"))
    return result


def style() -> str:
    return f"""  <style>
    text {{ font-family: \"Noto Sans SC\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif; fill: {PALETTE['ink']}; }}
    .section-label {{ font-size: 15px; font-weight: 600; letter-spacing: 0.04em; fill: {PALETTE['sub']}; }}
    .title {{ font-size: 20px; font-weight: 600; }}
    .body {{ font-size: 15px; fill: {PALETTE['sub']}; }}
    .small {{ font-size: 13px; fill: {PALETTE['sub']}; }}
    .node-label {{ font-size: 15px; font-weight: 600; }}
    .canvas {{ fill: #ffffff; }}
    .surface {{ fill: #ffffff; stroke: {PALETTE['line']}; stroke-width: 1.5; }}
    .input {{ fill: {PALETTE['input_fill']}; stroke: {PALETTE['input_line']}; stroke-width: 1.5; }}
    .mutable {{ fill: {PALETTE['mutable_fill']}; stroke: {PALETTE['mutable_line']}; stroke-width: 1.5; }}
    .protected {{ fill: {PALETTE['protected_fill']}; stroke: {PALETTE['protected_line']}; stroke-width: 1.5; }}
    .evidence {{ fill: {PALETTE['evidence_fill']}; stroke: {PALETTE['evidence_line']}; stroke-width: 1.5; }}
    .boundary {{ fill: {PALETTE['boundary_fill']}; stroke: {PALETTE['boundary_line']}; stroke-width: 1.5; stroke-dasharray: 7 6; }}
    .flow {{ fill: none; stroke: {PALETTE['line']}; stroke-width: 1.7; }}
    .arrow-fill {{ fill: {PALETTE['line']}; }}
  </style>"""


def render() -> str:
    svg = [
        '<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="768" viewBox="0 0 1200 720" role="img" aria-labelledby="title description">',
        "  <!-- Generated by tools/generate_architecture_svg.py. -->",
        "  <title id=\"title\">Evolve Framework architecture</title>",
        "  <desc id=\"description\">Recipes, target seeds, and Harbor datasets are frozen into a generated workspace. The protected Evolve mechanism orchestrates a composable operator loop while keeping the evaluator and runtime outside the evolvable surface. Git tags, archive records, and run artifacts retain the evidence.</desc>",
        style(),
        "",
        rect(0, 0, 1200, 720, 0, "canvas"),
        "",
        text("EXPERIMENT INPUTS", 60, 28, "section-label"),
        "",
    ]

    inputs = (
        (60, "Recipe", "operators + mutable surface"),
        (450, "Target seed", "agent, prompt, skills, or code"),
        (840, "Harbor dataset", "train + gate + sealed tasks"),
    )
    for x, title, subtitle in inputs:
        svg.extend(box(x, 45, 300, 76, "input", title, subtitle))
        svg.append("")

    svg.extend(
        [
            rect(40, 150, 1120, 430, 18, "boundary"),
            rect(60, 137, 282, 28, 14, "surface"),
            text("EVOLVE MECHANISM · PROTECTED", 201, 156, "section-label", "middle"),
            "",
            path("M 210 121 V 130 H 370 V 170 H 500"),
            arrow(500, 178, "down"),
            line(600, 121, 600, 169),
            arrow(600, 178, "down"),
            path("M 990 121 V 170 H 700"),
            arrow(700, 178, "down"),
            "",
            rect(410, 180, 380, 70, 12, "surface"),
            text("Initialize and freeze", 600, 210, "title", "middle"),
            text("render config · lock runtime · snapshot evaluator", 600, 233, "body", "middle"),
            "",
            path("M 600 250 V 276 H 325 V 285"),
            arrow(325, 294, "down"),
            path("M 600 250 V 276 H 875 V 285"),
            arrow(875, 294, "down"),
            "",
            rect(90, 300, 470, 134, 14, "mutable"),
            text("EVOLVABLE SURFACE", 115, 328, "section-label"),
            text("Target", 115, 361, "title"),
            text("agent code · prompt · skills · memory", 115, 385, "body"),
            text("Recipe-selected operators", 115, 410, "title"),
            text("only declared paths may change", 535, 428, "small", "end"),
            "",
            rect(640, 300, 470, 134, 14, "protected"),
            text("FROZEN RING", 665, 328, "section-label"),
            text("Evaluator + .evolve runtime", 665, 361, "title"),
            text("clean snapshots · task identity · score stamps", 665, 385, "body"),
            text("Archive integrity", 665, 410, "title"),
            text("candidates cannot rewrite evidence", 1085, 428, "small", "end"),
            "",
            line(325, 434, 325, 449),
            arrow(325, 458, "down"),
            line(875, 434, 875, 449),
            arrow(875, 458, "down"),
            "",
            text("COMPOSABLE EVOLUTION LOOP", 60, 478, "section-label"),
            "",
        ]
    )

    steps = (
        (60, "Select", "surface"),
        (218, "Rollout", "surface"),
        (376, "Analyze", "surface"),
        (534, "Edit", "mutable"),
        (692, "Evaluate", "protected"),
        (850, "Gate", "protected"),
        (1008, "Record", "evidence"),
    )
    for x, label, class_ in steps:
        svg.extend([rect(x, 493, 128, 54, 10, class_), text(label, x + 64, 526, "node-label", "middle")])
    svg.append("")

    for x1, x2 in zip((188, 346, 504, 662, 820, 978), (216, 374, 532, 690, 848, 1006), strict=True):
        svg.extend([line(x1, 520, x2 - 9, 520), arrow(x2, 520, "right")])
    svg.extend(
        [
            path("M 1072 547 V 562 H 124 V 558"),
            arrow(124, 549, "up"),
            "",
            line(1072, 562, 1072, 608),
            text("EVIDENCE AND LINEAGE", 60, 620, "section-label"),
            "",
        ]
    )

    evidence = ((60, "Git generation tags"), (450, "archive.jsonl"), (840, "Run artifacts and traces"))
    for x, label in evidence:
        svg.extend(box(x, 638, 300, 58, "evidence", label))
    svg.extend(
        [
            "",
            path("M 1072 608 H 210 V 629"),
            arrow(210, 638, "down"),
            line(600, 608, 600, 629),
            arrow(600, 638, "down"),
            path("M 1072 608 H 990 V 629"),
            arrow(990, 638, "down"),
            "</svg>",
        ]
    )
    return "\n".join(svg) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the README architecture diagram.")
    parser.add_argument("--check", action="store_true", help="Fail if docs/architecture.svg is not up to date.")
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date; regenerate it with {Path(__file__).relative_to(ROOT)}")
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is up to date")
        return 0
    OUTPUT.write_text(generated)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
